spring:
  application:
    name: user-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  cloud:
    config:
      label: ${CONFIG_LABEL:develop}
      fail-fast: true
